# Generated by Django 5.1.6 on 2025-03-06 10:33

import django.db.models.deletion
import image_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medialib", "0004_alter_albumorder_id_alter_attachments_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tmp_file", models.FileField(null=True, upload_to="")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (
                                image_processing.models.TaskStatusEnum["PROCESSING"],
                                "Processing…",
                            ),
                            (image_processing.models.TaskStatusEnum["DONE"], "Done!"),
                            (
                                image_processing.models.TaskStatusEnum["ERROR"],
                                "ERROR!!!",
                            ),
                        ]
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medialib.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionError",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=128)),
                ("details", models.TextField(null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_file_size", models.PositiveBigIntegerField()),
                ("result_file_size", models.PositiveBigIntegerField()),
                ("quality", models.SmallIntegerField()),
                ("lossless", models.BooleanField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.task",
                    ),
                ),
            ],
        ),
    ]
