# Generated by Django 6.0 on 2026-02-11 18:06

from media_receiving import models as mr_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (
                        mr_models.TaskStatusEnum["AWAITING"],
                        "Wait for processing…",
                    ),
                    (mr_models.TaskStatusEnum["DONE"], "Done!"),
                    (mr_models.TaskStatusEnum["ERROR"], "ERROR!!!"),
                    (mr_models.TaskStatusEnum["PROCESSING"], "Processing…"),
                ],
                default=mr_models.TaskStatusEnum["AWAITING"],
            ),
        ),
    ]
