# Generated by Django 6.0 on 2026-02-11 18:06

import image_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(image_processing.models.TaskStatusEnum['AWAITING'], 'Wait for processing…'), (image_processing.models.TaskStatusEnum['DONE'], 'Done!'), (image_processing.models.TaskStatusEnum['ERROR'], 'ERROR!!!'), (image_processing.models.TaskStatusEnum['PROCESSING'], 'Processing…')], default=image_processing.models.TaskStatusEnum['AWAITING']),
        ),
    ]
