# Generated by Django 5.1.6 on 2025-03-14 10:11

import django.db.models.deletion
import image_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="content",
        ),
        migrations.AlterField(
            model_name="executionerror",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="image_processing.task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (
                        image_processing.models.TaskStatusEnum["AWAITING"],
                        "Wait for processing…",
                    ),
                    (image_processing.models.TaskStatusEnum["DONE"], "Done!"),
                    (image_processing.models.TaskStatusEnum["ERROR"], "ERROR!!!"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tmp_file",
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="image_processing.task"
            ),
        ),
        migrations.CreateModel(
            name="ContentRepresentation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filepath", models.FilePathField(unique=True)),
                ("format", models.CharField(max_length=12)),
                (
                    "compatibility_level",
                    models.PositiveSmallIntegerField(
                        verbose_name="Compatibility level"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.taskresult",
                    ),
                ),
            ],
        ),
    ]
