# Generated by Django 6.0 on 2025-12-13 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_remove_task_content_alter_executionerror_task_and_more'),
        ('medialib', '0007_remove_contenttotagsrelationship_unique_tag_to_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='lossless',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='quality',
        ),
        migrations.AddField(
            model_name='taskresult',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medialib.content'),
        ),
        migrations.AlterField(
            model_name='executionerror',
            name='details',
            field=models.TextField(help_text='Detailed description of error. Likely to be exception stack trace', null=True),
        ),
        migrations.AlterField(
            model_name='executionerror',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='executionerror',
            name='title',
            field=models.TextField(help_text='The name of the error'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ContentRepresentation',
        ),
    ]
