# Generated by Django 6.0 on 2026-02-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionerror',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.task'),
        ),
    ]
