# Generated by Django 6.0 on 2025-12-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_remove_taskresult_lossless_remove_taskresult_quality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwaitingTaskMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('origin_name', models.CharField(max_length=32, null=True)),
                ('origin_id', models.TextField()),
                ('tags', models.JSONField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_processing.task')),
            ],
        ),
    ]
