# Generated by Django 6.0.3 on 2026-04-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_alter_executionerror_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionerror',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='content',
        ),
        migrations.DeleteModel(
            name='AwaitingTaskMetadata',
        ),
        migrations.DeleteModel(
            name='ExecutionError',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
