# Generated by Django 6.0 on 2025-12-29 18:05

import image_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_awaitingtaskmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='origin_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(image_processing.models.TaskStatusEnum['AWAITING'], 'Wait for processing…'), (image_processing.models.TaskStatusEnum['DONE'], 'Done!'), (image_processing.models.TaskStatusEnum['ERROR'], 'ERROR!!!')], default=image_processing.models.TaskStatusEnum['AWAITING']),
        ),
    ]
