# Generated by Django 6.0 on 2026-01-02 19:11

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0005_alter_awaitingtaskmetadata_origin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tmp_file',
        ),
        migrations.AddField(
            model_name='task',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mime_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to=pathlib.PurePosixPath('queue')),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='origin_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='origin_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
