# Generated by Django 6.0 on 2026-01-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0006_remove_task_tmp_file_task_media_type_task_mime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
