# Generated by Django 6.0 on 2026-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0007_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='origin_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='awaitingtaskmetadata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
