# Generated by Django 6.0 on 2026-01-08 14:07

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0008_alter_awaitingtaskmetadata_origin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uploaded_file',
            field=models.FileField(max_length=512, null=True, upload_to=pathlib.PurePosixPath('queue')),
        ),
    ]
