services:
  db:
    image: postgres:18
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql${VOLUME_FLAGS:-}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:8-alpine
    restart: always

  web:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS:-4} medialib_v2.wsgi:application
    volumes:
      - ${MEDIALIB_STORAGE_PATH:-./media}:/app/media${VOLUME_FLAGS:-}
    env_file:
      - .env
      - .env.docker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    security_opt:
      - label:disable

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${HOST_PORT:-8829}:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ${MEDIALIB_STORAGE_PATH:-./media}:/app/media:ro
    depends_on:
      - web

  celery:
    build: .
    restart: always
    command: celery -A medialib_v2 worker --loglevel=info
    volumes:
      - ${MEDIALIB_STORAGE_PATH:-./media}:/app/media${VOLUME_FLAGS:-}
    env_file:
      - .env
      - .env.docker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    security_opt:
      - label:disable

volumes:
  postgres_data:
  media_volume:
