[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "medialib_v2"
version = "1.0.0" # version of next tag (release)
description = "A powerful media library with auto-tagging, hashing, and transcoding capabilities."
readme = "README.md"
authors = [
    {name = "mfg637", email = "mfg636@gmail.com"},
]
license = {text = "MIT"}
requires-python = ">=3.14.2"
keywords = ["media", "image-processing", "django"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "Django",
    "ImageHash",
    "psycopg2-binary",
    "python-magic",
    "Pillow",
    "mypy",
    "django-stubs",
    "scikit-image",
    "pyvips",
    "python-dotenv",
    "celery",
    "redis",
    "Markdown",
    "requests",
    "gunicorn",
    "whitenoise",
    "xxhash",
]

#[project.urls] # project is not published yet
#Homepage = "https://github.com/your-username/medialib_v2"
#"Bug Tracker" = "https://github.com/your-username/medialib_v2/issues"

[tool.black]
line-length = 79
target-version = ['py314']

[tool.isort]
profile = "black"

[tool.pyenv]
version = "3.14.2"
environment = "/home/mfg637/.pyenv/versions/3.14.2/envs/medialib_v2"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "medialib_v2.settings"
