# Generated by Django 5.1.6 on 2025-03-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("medialib", "0001_initial"),
        ("medialib", "0002_remove_albumorder_unique_content_to_album_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "filepath",
                    models.FilePathField(
                        allow_folders=True,
                        recursive=True,
                        unique=True,
                        verbose_name="/home/mfg637/pictures/medialib",
                    ),
                ),
                ("title", models.CharField(max_length=64, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("video-loop", "Video-loop"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "addition_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("last_edit", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=240)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("prompter", "Prompter"),
                            ("generator", "AI Generation model"),
                            ("set", "Unordered set"),
                            ("copyright", "Copyright"),
                            ("rating", "Rating"),
                            ("species", "Species"),
                            ("character", "Character name"),
                            ("content", "Content description"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "album_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="album_set",
                        to="medialib.tag",
                    ),
                ),
                (
                    "artist_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artist_tag",
                        to="medialib.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagImplications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "implicate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implicated_tag",
                        to="medialib.tag",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_tag",
                        to="medialib.tag",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target", "implicate"), name="unique_tag_to_implication"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attachments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filepath",
                    models.FilePathField(
                        allow_folders=True,
                        db_index=True,
                        recursive=True,
                        unique=True,
                        verbose_name="/home/mfg637/pictures/medialib",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("format", models.CharField(max_length=12)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "origin_id",
                    models.CharField(max_length=128, verbose_name="ID on origin"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspect_ratio", models.FloatField(verbose_name="Aspect Ratio")),
                (
                    "value_hash",
                    models.BinaryField(
                        db_index=True,
                        max_length=256,
                        verbose_name="Value component hash",
                    ),
                ),
                (
                    "hue_hash",
                    models.BigIntegerField(
                        db_index=True, verbose_name="Hue component hash"
                    ),
                ),
                (
                    "saturation_hash",
                    models.BigIntegerField(
                        db_index=True, verbose_name="Saturation component hash"
                    ),
                ),
                (
                    "alternate_version",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Representation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filepath",
                    models.FilePathField(
                        allow_folders=True,
                        recursive=True,
                        unique=True,
                        verbose_name="/home/mfg637/pictures/medialib",
                    ),
                ),
                ("format", models.CharField(max_length=12)),
                (
                    "compatibility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Supercomputer"),
                            (1, "Personal Computer"),
                            (2, "Powerfull mobile device"),
                            (3, "Dated mobile device"),
                            (4, "Old hardware"),
                        ],
                        verbose_name="Compatibility level",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medialib.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filepath",
                    models.FilePathField(
                        unique=True,
                        verbose_name="/home/mfg637/.cache/thumbnails/medialib-db-thumbnails",
                    ),
                ),
                ("width", models.PositiveSmallIntegerField()),
                ("height", models.PositiveSmallIntegerField()),
                (
                    "generation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of generation"
                    ),
                ),
                ("format", models.CharField(max_length=12)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbumOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medialib.album"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("album", "content"), name="unique_content_to_album"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentToTagsRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medialib.tag"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content", "tag"), name="unique_tag_to_content"
                    )
                ],
            },
        ),
    ]
