# Generated by Django 6.0 on 2026-02-06 15:25

import base.shared_enums.medialib_model
import django.db.models.deletion
import medialib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[(base.shared_enums.medialib_model.ContentTypeEnum['IMAGE'], 'Image'), (base.shared_enums.medialib_model.ContentTypeEnum['AUDIO'], 'Audio'), (base.shared_enums.medialib_model.ContentTypeEnum['VIDEO'], 'Video'), (base.shared_enums.medialib_model.ContentTypeEnum['VIDEO_LOOP'], 'Video-loop')], default=base.shared_enums.medialib_model.ContentTypeEnum['IMAGE'], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('addition_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('source_hash', models.BinaryField(db_index=True, help_text='SHA-256 hash of the original file content (stored as BYTEA).', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'content',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=12)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.content')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.album')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.content')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='contents',
            field=models.ManyToManyField(related_name='albums', through='medialib.AlbumOrder', through_fields=('album', 'content'), to='medialib.content'),
        ),
        migrations.CreateModel(
            name='ContentOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('origin_id', models.TextField(blank=True, default='', verbose_name='ID on origin')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.content')),
            ],
        ),
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.FloatField(verbose_name='Aspect Ratio')),
                ('L_hash', models.BinaryField(db_index=True, max_length=32, verbose_name='Lightness component hash')),
                ('a_hash', models.BinaryField(db_index=True, max_length=8, verbose_name='a* component hash')),
                ('b_hash', models.BinaryField(db_index=True, max_length=8, verbose_name='b* component hash')),
                ('alternate_version', models.BooleanField(db_index=True, default=False)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medialib.content')),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(max_length=512, unique=True, upload_to='medialib/%Y/%m/%d')),
                ('format', models.CharField(max_length=12)),
                ('compatibility_level', models.PositiveSmallIntegerField(choices=[(4, 'Supercomputer'), (3, 'Personal Computer'), (2, 'Mobile device'), (1, 'Old hardware'), (0, 'Very old hardware')], verbose_name='Compatibility level')),
                ('generation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('width', models.PositiveSmallIntegerField(null=True)),
                ('height', models.PositiveSmallIntegerField(null=True)),
                ('repr_type', models.IntegerField(choices=[(0, 'Audio'), (10, 'Image'), (20, 'Video')])),
                ('codec_string', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.content')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[(medialib.models.CategoryEnum['CREATOR'], 'Content creator'), (medialib.models.CategoryEnum['ARTIST'], 'Artist'), (medialib.models.CategoryEnum['PROMPTER'], 'Prompter'), (medialib.models.CategoryEnum['AI'], 'AI related metadata'), (medialib.models.CategoryEnum['SET'], 'Unordered set'), (medialib.models.CategoryEnum['COMIC'], 'Comic pages set'), (medialib.models.CategoryEnum['COPYRIGHT'], 'Copyright'), (medialib.models.CategoryEnum['RATING'], 'Rating'), (medialib.models.CategoryEnum['SPECIES'], 'Species'), (medialib.models.CategoryEnum['CHARACTER'], 'Character name'), (medialib.models.CategoryEnum['CHARACTER_GROUP'], 'Group of characters'), (medialib.models.CategoryEnum['GENDER'], 'Gender'), (medialib.models.CategoryEnum['LORE'], 'Lore metadata'), (medialib.models.CategoryEnum['META'], 'Metadata'), (medialib.models.CategoryEnum['ERROR'], 'Error'), (medialib.models.CategoryEnum['STYLE'], 'Style description'), (medialib.models.CategoryEnum['CONTENT'], 'Content description')], db_index=True)),
                ('content', models.ManyToManyField(to='medialib.content')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='album_set', to='medialib.tag'),
        ),
        migrations.AddField(
            model_name='album',
            name='creator_tags',
            field=models.ManyToManyField(related_name='creator_albums', to='medialib.tag'),
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, unique=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialib.tag')),
            ],
            options={
                'verbose_name': 'alias of tag',
                'verbose_name_plural': 'aliases of tag',
            },
        ),
        migrations.CreateModel(
            name='TagImplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications_implicated', to='medialib.tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications_target', to='medialib.tag')),
            ],
            options={
                'verbose_name': 'implication of tag',
                'verbose_name_plural': 'implications of tag',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='implications',
            field=models.ManyToManyField(related_name='is_implied_by', through='medialib.TagImplications', through_fields=('target', 'implicate'), to='medialib.tag'),
        ),
        migrations.AddConstraint(
            model_name='albumorder',
            constraint=models.UniqueConstraint(fields=('album', 'content'), name='unique_content_to_album'),
        ),
        migrations.AlterUniqueTogether(
            name='albumorder',
            unique_together={('album', 'order')},
        ),
        migrations.AddConstraint(
            model_name='tagimplications',
            constraint=models.UniqueConstraint(fields=('target', 'implicate'), name='unique_tag_to_implication'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('title', 'category'), name='unique_tag_title_category'),
        ),
    ]
