# Generated by Django 5.1.6 on 2025-03-03 10:44

import medialib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0001_initial_squashed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagalias",
            options={
                "verbose_name": "Alias of tag",
                "verbose_name_plural": "Aliases of tag",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    (medialib.models.CategoryEnum["ARTIST"], "Artist"),
                    (medialib.models.CategoryEnum["PROMPTER"], "Prompter"),
                    ("generator", "AI Generation model"),
                    (medialib.models.CategoryEnum["SET"], "Unordered set"),
                    (medialib.models.CategoryEnum["COPYRIGHT"], "Copyright"),
                    (medialib.models.CategoryEnum["RATING"], "Rating"),
                    (medialib.models.CategoryEnum["SPECIES"], "Species"),
                    (
                        medialib.models.CategoryEnum["CHARACTER"],
                        "Character name",
                    ),
                    (medialib.models.CategoryEnum["GENDER"], "Gender"),
                    (
                        medialib.models.CategoryEnum["CONTENT"],
                        "Content description",
                    ),
                ],
                max_length=10,
            ),
        ),
    ]
