# Generated by Django 5.1.6 on 2025-03-06 07:44

import medialib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0002_alter_tagalias_options_alter_tag_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagalias",
            options={
                "verbose_name": "alias of tag",
                "verbose_name_plural": "aliases of tag",
            },
        ),
        migrations.AlterModelOptions(
            name="tagimplications",
            options={
                "verbose_name": "implication of tag",
                "verbose_name_plural": "implications of tag",
            },
        ),
        migrations.RemoveField(
            model_name="content",
            name="filepath",
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    (medialib.models.ContentTypeEnum["IMAGE"], "Image"),
                    (medialib.models.ContentTypeEnum["AUDIO"], "Audio"),
                    (medialib.models.ContentTypeEnum["VIDEO"], "Video"),
                    (medialib.models.ContentTypeEnum["VIDEO_LOOP"], "Video-loop"),
                    (medialib.models.ContentTypeEnum["TEXT"], "Text content"),
                ],
                default=medialib.models.ContentTypeEnum["TEXT"],
                max_length=10,
            ),
        ),
    ]
