# Generated by Django 5.1.6 on 2025-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medialib",
            "0003_alter_tagalias_options_alter_tagimplications_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumorder",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="attachments",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contenttotagsrelationship",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="imagehash",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="representation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tagalias",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tagimplications",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
