# Generated by Django 5.1.6 on 2025-03-13 13:45

import medialib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0004_alter_albumorder_id_alter_attachments_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "content", "verbose_name_plural": "content"},
        ),
        migrations.AlterField(
            model_name="attachments",
            name="filepath",
            field=models.FilePathField(
                allow_folders=True, db_index=True, recursive=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    (medialib.models.ContentTypeEnum["IMAGE"], "Image"),
                    (medialib.models.ContentTypeEnum["AUDIO"], "Audio"),
                    (medialib.models.ContentTypeEnum["VIDEO"], "Video"),
                    (medialib.models.ContentTypeEnum["VIDEO_LOOP"], "Video-loop"),
                ],
                default=medialib.models.ContentTypeEnum["IMAGE"],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="representation",
            name="filepath",
            field=models.FilePathField(allow_folders=True, recursive=True, unique=True),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="filepath",
            field=models.FilePathField(unique=True),
        ),
    ]
