# Generated by Django 6.0 on 2026-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0001_initial_squashed_0005_alter_tagalias_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='compatibility_level',
            field=models.PositiveSmallIntegerField(choices=[(4, 'CL4 Supercomputer'), (3, 'CL3 Personal Computer'), (2, 'CL2 Mobile device'), (1, 'CL1 Old hardware'), (0, 'CL0 Very old hardware')], verbose_name='Compatibility level'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='repr_type',
            field=models.IntegerField(choices=[(10, 'Image'), (20, 'Video'), (0, 'Audio')]),
        ),
    ]
