# Generated by Django 5.1.6 on 2025-03-14 10:11

import django.db.models.deletion
import medialib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "image_processing",
            "0002_remove_task_content_alter_executionerror_task_and_more",
        ),
        (
            "medialib",
            "0005_alter_content_options_alter_attachments_filepath_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachments",
            name="filepath",
            field=models.FilePathField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="representation",
            name="filepath",
            field=models.FilePathField(unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    (medialib.models.CategoryEnum["ARTIST"], "Artist"),
                    (medialib.models.CategoryEnum["PROMPTER"], "Prompter"),
                    ("generator", "AI Generation model"),
                    (medialib.models.CategoryEnum["SET"], "Unordered set"),
                    (medialib.models.CategoryEnum["COPYRIGHT"], "Copyright"),
                    (medialib.models.CategoryEnum["RATING"], "Rating"),
                    (medialib.models.CategoryEnum["SPECIES"], "Species"),
                    (
                        medialib.models.CategoryEnum["CHARACTER"],
                        "Character name",
                    ),
                    (medialib.models.CategoryEnum["GENDER"], "Gender"),
                    (
                        medialib.models.CategoryEnum["CONTENT"],
                        "Content description",
                    ),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ContentToTaskRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medialib.content",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.task",
                    ),
                ),
            ],
        ),
    ]
