# Generated by Django 6.0 on 2026-02-13 10:46

from django.db import migrations


class Migration(migrations.Migration):
    @staticmethod
    def gen_slugs(apps, schema_editor):
        Content = apps.get_model("medialib", "Content")
        for obj in Content.objects.all():
            date_str = obj.addition_date.strftime("%Y-%m-%d")
            hash_str = obj.source_hash.tobytes().hex()
            obj.slug = f"{date_str}-{hash_str}"
            obj.save()

    dependencies = [
        ("medialib", "0006_content_slug_and_more"),
    ]

    operations = [migrations.RunPython(gen_slugs)]
