# Generated by Django 6.0 on 2025-12-13 21:56

import django.db.models.deletion
import django.utils.timezone
import medialib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0006_alter_attachments_filepath_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contenttotagsrelationship',
            name='unique_tag_to_content',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='content',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist_set',
        ),
        migrations.AddField(
            model_name='album',
            name='album_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='contents',
            field=models.ManyToManyField(related_name='albums', through='medialib.AlbumOrder', through_fields=('album', 'content'), to='medialib.content'),
        ),
        migrations.AddField(
            model_name='album',
            name='creator_tags',
            field=models.ManyToManyField(related_name='creator_albums', to='medialib.tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='source_hash',
            field=models.BinaryField(db_index=True, help_text='SHA-256 hash of the original file content (stored as BYTEA).', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='representation',
            name='generation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representation',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='representation',
            name='repr_type',
            field=models.IntegerField(choices=[(0, 'Audio'), (10, 'Image'), (20, 'Video')], null=True),
        ),
        migrations.AddField(
            model_name='representation',
            name='width',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.ManyToManyField(to='medialib.content'),
        ),
        migrations.AddField(
            model_name='tag',
            name='implications',
            field=models.ManyToManyField(related_name='is_implied_by', through='medialib.TagImplications', through_fields=('target', 'implicate'), to='medialib.tag'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='album_set', to='medialib.tag'),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentorigin',
            name='origin_id',
            field=models.TextField(verbose_name='ID on origin'),
        ),
        migrations.AlterField(
            model_name='imagehash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='compatibility_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Supercomputer'), (1, 'Personal Computer'), (2, 'Mobile device'), (3, 'Old hardware'), (4, 'Very old hardware')], verbose_name='Compatibility level'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[(medialib.models.CategoryEnum['CREATOR'], 'Content creator'), (medialib.models.CategoryEnum['ARTIST'], 'Artist'), (medialib.models.CategoryEnum['PROMPTER'], 'Prompter'), (medialib.models.CategoryEnum['AI'], 'AI related metadata'), (medialib.models.CategoryEnum['SET'], 'Unordered set'), (medialib.models.CategoryEnum['COMIC'], 'Comic pages set'), (medialib.models.CategoryEnum['COPYRIGHT'], 'Copyright'), (medialib.models.CategoryEnum['RATING'], 'Rating'), (medialib.models.CategoryEnum['SPECIES'], 'Species'), (medialib.models.CategoryEnum['CHARACTER'], 'Character name'), (medialib.models.CategoryEnum['CHARACTER_GROUP'], 'Group of characters'), (medialib.models.CategoryEnum['GENDER'], 'Gender'), (medialib.models.CategoryEnum['LORE'], 'Lore metadata'), (medialib.models.CategoryEnum['META'], 'Metadata'), (medialib.models.CategoryEnum['ERROR'], 'Error'), (medialib.models.CategoryEnum['STYLE'], 'Style description'), (medialib.models.CategoryEnum['CONTENT'], 'Content description')], db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='title',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tagimplications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tagimplications',
            name='implicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications_implicated', to='medialib.tag'),
        ),
        migrations.AlterField(
            model_name='tagimplications',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications_target', to='medialib.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='albumorder',
            unique_together={('album', 'order')},
        ),
        migrations.RemoveField(
            model_name='contenttotagsrelationship',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contenttotagsrelationship',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ContentToTaskRelationship',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
        migrations.DeleteModel(
            name='ContentToTagsRelationship',
        ),
    ]
