# Generated by Django 6.0 on 2025-12-13 21:57

from django.db import migrations


MAPPING = {
    "image": 10,
    "audio": 0,
    "video": 20,
    "video-loop": 20,
}


def set_default_repr_type(apps, schema_editor):
    Representation = apps.get_model("medialib", "Representation")
    Content = apps.get_model("medialib", "Content")

    content_map = dict(Content.objects.values_list("id", "content_type"))

    updates = []
    for rep in Representation.objects.all():
        content_type = content_map.get(rep.content_id)
        if content_type:
            rep.repr_type = MAPPING.get(content_type, MAPPING["image"])
            updates.append(rep)

    Representation.objects.bulk_update(updates, ["repr_type"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "medialib",
            "0007_remove_contenttotagsrelationship_unique_tag_to_content_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            set_default_repr_type, reverse_code=migrations.RunPython.noop
        ),
    ]
