# Generated by Django 6.0 on 2026-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0007_auto_20260213_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, unique=True),
        ),
    ]
