# Generated by Django 6.0 on 2026-02-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0008_alter_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_set', to='medialib.content'),
        ),
    ]
