# Generated by Django 6.0 on 2025-12-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0008_auto_20251213_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='repr_type',
            field=models.IntegerField(choices=[(0, 'Audio'), (10, 'Image'), (20, 'Video')]),
        ),
    ]
