# Generated by Django 6.0 on 2026-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0009_alter_representation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentorigin',
            name='origin_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID on origin'),
        ),
        migrations.AddIndex(
            model_name='contentorigin',
            index=models.Index(fields=['name', 'origin_id'], name='medialib_co_name_7f5506_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentorigin',
            constraint=models.UniqueConstraint(condition=models.Q(('origin_id', ''), _negated=True), fields=('name', 'origin_id'), name='unique_origin_source_id'),
        ),
    ]
