# Generated by Django 6.0 on 2026-03-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0010_alter_contentorigin_origin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorigin',
            name='alternate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentorigin',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_set', to='medialib.content'),
        ),
    ]
