# Generated by Django 6.0.3 on 2026-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0011_contentorigin_alternate_alter_contentorigin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehash',
            name='search_similar',
            field=models.BinaryField(db_index=True, max_length=8, null=True),
        ),
        migrations.AddIndex(
            model_name='imagehash',
            index=models.Index(fields=['L_hash', 'a_hash', 'b_hash'], name='medialib_im_L_hash_2d591e_idx'),
        ),
    ]
