# Generated by Django 6.0.3 on 2026-03-03 17:25

from django.db import migrations


def fill_search_similar(apps, schema_editor):
    ImageHash = apps.get_model("medialib", "ImageHash")
    for ih in ImageHash.objects.all():
        ih.search_similar = (
            bytes(ih.L_hash)[:4] + bytes(ih.a_hash)[:2] + bytes(ih.b_hash)[:2]
        )
        ih.save(update_fields=["search_similar"])


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0012_imagehash_search_similar_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_search_similar),
    ]
