# Generated by Django 6.0.3 on 2026-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0013_auto_20260303_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehash',
            name='search_similar',
            field=models.BinaryField(db_index=True, max_length=8),
        ),
    ]
