# Generated by Django 6.0.3 on 2026-03-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0014_alter_imagehash_search_similar'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehash',
            name='far_similarity',
            field=models.BinaryField(db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='imagehash',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagehash', to='medialib.content'),
        ),
    ]
