# Generated by Django 6.0.3 on 2026-03-03 18:47

from django.db import migrations


def fill_far_similarity(apps, schema_editor):
    ImageHash = apps.get_model("medialib", "ImageHash")
    for ih in ImageHash.objects.all():
        ih.far_similarity = (
            bytes(ih.L_hash)[:2] + bytes(ih.a_hash)[:1] + bytes(ih.b_hash)[:1]
        )
        ih.save(update_fields=["far_similarity"])


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0015_imagehash_far_similarity_alter_imagehash_content"),
    ]

    operations = [
        migrations.RunPython(fill_far_similarity),
    ]
