# Generated by Django 6.0.3 on 2026-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0016_auto_20260303_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehash',
            name='far_similarity',
            field=models.BinaryField(db_index=True, max_length=4),
        ),
    ]
