# Generated by Django 6.0.3 on 2026-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0018_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
