# Generated by Django 6.0.3 on 2026-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0019_collection_is_nsfw'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumorder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='albumorder',
            constraint=models.UniqueConstraint(fields=('album', 'order'), name='unique_album_order_position'),
        ),
    ]
