# Generated by Django 6.0.3 on 2026-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0020_alter_albumorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='creator_tags',
            field=models.ManyToManyField(blank=True, related_name='creator_albums', to='medialib.tag'),
        ),
    ]
