# Generated by Django 6.0.3 on 2026-03-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0021_album_is_nsfw_alter_album_creator_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='album_set', to='medialib.tag'),
        ),
    ]
