# Generated by Django 6.0.3 on 2026-03-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0022_alter_album_album_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medialib.album'),
        ),
    ]
