# Generated by Django 6.0.3 on 2026-03-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0023_alter_albumorder_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_item', to='medialib.content'),
        ),
    ]
