# Generated by Django 6.0.3 on 2026-04-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0024_alter_albumorder_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehash',
            options={'verbose_name': 'Image Hash', 'verbose_name_plural': 'Image Hashes'},
        ),
    ]
