# Generated by Django 6.0.3 on 2026-04-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0025_alter_imagehash_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=75, unique=True)),
                ('created_at', models.DateTimeField()),
                ('source_hash', models.BinaryField(db_index=True, help_text='SHA-256 hash of the original file content (stored as BYTEA).', max_length=32, unique=True)),
                ('new_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redirects', to='medialib.content')),
            ],
        ),
    ]
