# Generated by Django 6.0.3 on 2026-04-21 13:20

from django.db import migrations
from base.shared_enums.medialib_model import CategoryEnum


def create_default_tags(apps, schema_editor):
    Tag = apps.get_model("medialib", "Tag")
    TagImplications = apps.get_model("medialib", "TagImplications")
    safe_tag, _ = Tag.objects.get_or_create(
        title="safe", category=CategoryEnum.RATING.value
    )
    safe_tag.alias_set.get_or_create(title="safe")
    vector_tag, _ = Tag.objects.get_or_create(
        title="vector", category=CategoryEnum.CONTENT.value
    )
    vector_tag.alias_set.get_or_create(title="vector")
    sketch_tag, _ = Tag.objects.get_or_create(
        title="sketch", category=CategoryEnum.STYLE.value
    )
    sketch_tag.alias_set.get_or_create(title="sketch")
    simple_bg_tag, _ = Tag.objects.get_or_create(
        title="simple background", category=CategoryEnum.CONTENT.value
    )
    simple_bg_tag.alias_set.get_or_create(title="simple background")
    simple_bg_tag.alias_set.get_or_create(title="simple_background")
    screencap_tag, _ = Tag.objects.get_or_create(
        title="screencap", category=CategoryEnum.META.value
    )
    screencap_tag.alias_set.get_or_create(title="screencap")
    photo_tag, _ = Tag.objects.get_or_create(
        title="photography (artwork)", category=CategoryEnum.META.value
    )
    photo_tag.alias_set.get_or_create(title="photography (artwork)")
    photo_tag.alias_set.get_or_create(title="photography_(artwork)")
    photo_tag.alias_set.get_or_create(title="photo")
    ai_content_tag, _ = Tag.objects.get_or_create(
        title="ai content", category=CategoryEnum.AI.value
    )
    ai_content_tag.alias_set.get_or_create(title="ai content")
    ai_content_tag.alias_set.get_or_create(title="ai_content")
    ai_generated_tag, _ = Tag.objects.get_or_create(
        title="ai generated", category=CategoryEnum.AI.value
    )
    ai_generated_tag.alias_set.get_or_create(title="ai: ai generated")
    ai_generated_tag.alias_set.get_or_create(title="ai:generated")
    TagImplications.objects.get_or_create(
        target=ai_generated_tag, implicate=ai_content_tag
    )
    comic_tag, _ = Tag.objects.get_or_create(
        title="comic", category=CategoryEnum.META.value
    )
    comic_tag.alias_set.get_or_create(title="comic")


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0026_contentredirect"),
    ]

    operations = [migrations.RunPython(create_default_tags)]
