# Generated by Django 6.0.3 on 2026-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0027_auto_20260421_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='hash',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
