# Generated by Django 6.0.3 on 2026-04-28 12:28

from django.db import migrations
from image_processing.core.file_utils import calc_xxh3_64
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


def fill_representation_hashes(apps, schema_editor):
    Representation = apps.get_model("medialib", "Representation")

    for obj in Representation.objects.all():
        if obj.filepath and not obj.hash:
            filepath = Path(obj.filepath.path)
            if filepath.exists():
                obj.hash = calc_xxh3_64(filepath)
                obj.save(update_fields=["hash"])
            else:
                logger.warning("File not found: %s", filepath)


class Migration(migrations.Migration):

    dependencies = [
        ("medialib", "0028_representation_hash"),
    ]

    operations = [
        migrations.RunPython(fill_representation_hashes),
    ]
