# Generated by Django 6.0.3 on 2026-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0029_auto_20260428_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='hash',
            field=models.BigIntegerField(default=None),
        ),
    ]
