# Generated by Django 6.0.3 on 2026-04-09 13:55

import django.db.models.deletion
import media_receiving.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medialib', '0025_alter_imagehash_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(max_length=512, null=True, upload_to=pathlib.PurePosixPath('queue'))),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('source_hash', models.BinaryField(db_index=True, help_text='SHA-256 hash of the original file content (stored as BYTEA).', max_length=32, unique=True)),
                ('status', models.IntegerField(choices=[(media_receiving.models.TaskStatusEnum['AWAITING'], 'Wait for processing…'), (media_receiving.models.TaskStatusEnum['DONE'], 'Done!'), (media_receiving.models.TaskStatusEnum['ERROR'], 'ERROR!!!'), (media_receiving.models.TaskStatusEnum['PROCESSING'], 'Processing…')], default=media_receiving.models.TaskStatusEnum['AWAITING'])),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='The name of the error')),
                ('details', models.TextField(blank=True, default='', help_text='Detailed description of error. Likely to be exception stack trace')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='media_receiving.task')),
            ],
        ),
        migrations.CreateModel(
            name='AwaitingTaskMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('origin_name', models.CharField(blank=True, default='', max_length=32)),
                ('origin_id', models.CharField(blank=True, default='', max_length=512)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='media_receiving.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_size', models.PositiveBigIntegerField()),
                ('result_file_size', models.PositiveBigIntegerField()),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_results', to='medialib.content')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='media_receiving.task')),
            ],
        ),
    ]
