# Generated by Django 6.0.3 on 2026-04-09 14:04

from django.db import migrations, connection


def copy_tasks_data(apps, schema_editor):
    OldTask = apps.get_model("image_processing", "Task")
    NewTask = apps.get_model("media_receiving", "Task")

    OldMetadata = apps.get_model("image_processing", "AwaitingTaskMetadata")
    NewMetadata = apps.get_model("media_receiving", "AwaitingTaskMetadata")

    OldResult = apps.get_model("image_processing", "TaskResult")
    NewResult = apps.get_model("media_receiving", "TaskResult")

    OldError = apps.get_model("image_processing", "ExecutionError")
    NewError = apps.get_model("media_receiving", "ExecutionError")

    for old_task in OldTask.objects.all():
        new_task = NewTask.objects.create(
            id=old_task.id,
            created_at=old_task.created_at,
            uploaded_file=old_task.uploaded_file,
            media_type=old_task.media_type,
            mime_type=old_task.mime_type,
            source_hash=old_task.source_hash,
            status=old_task.status,
        )

        old_meta = OldMetadata.objects.filter(task=old_task).first()
        if old_meta:
            NewMetadata.objects.create(
                task=new_task,
                title=old_meta.title,
                description=old_meta.description,
                origin_name=old_meta.origin_name,
                origin_id=old_meta.origin_id,
                tags=old_meta.tags,
            )

        old_res = OldResult.objects.filter(task=old_task).first()
        if old_res:
            NewResult.objects.create(
                task=new_task,
                content=old_res.content,
                source_file_size=old_res.source_file_size,
                result_file_size=old_res.result_file_size,
            )

        for old_err in OldError.objects.filter(task=old_task):
            NewError.objects.create(
                task=new_task, title=old_err.title, details=old_err.details
            )

    from django.core.management.color import no_style

    new_models = [
        apps.get_model("media_receiving", "Task"),
        apps.get_model("media_receiving", "TaskResult"),
        apps.get_model("media_receiving", "AwaitingTaskMetadata"),
        apps.get_model("media_receiving", "ExecutionError"),
    ]

    sequence_sql = connection.ops.sequence_reset_sql(no_style(), new_models)

    with connection.cursor() as cursor:
        for sql in sequence_sql:
            cursor.execute(sql)


def reverse_copy(apps, schema_editor):
    NewTask = apps.get_model("media_receiving", "Task")
    NewTask.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("media_receiving", "0001_initial"),
        ("image_processing", "0003_alter_executionerror_task"),
    ]

    operations = [
        migrations.RunPython(copy_tasks_data, reverse_copy),
    ]
