# Generated by Django 6.0.3 on 2026-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_receiving', '0002_auto_20260409_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rewrite',
            field=models.BooleanField(default=False, help_text='If enabled, skips deduplication validation and updates existing content', verbose_name='Rewrite existing content'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_hash',
            field=models.BinaryField(db_index=True, help_text='SHA-256 hash of the original file content (stored as BYTEA).', max_length=32),
        ),
    ]
