# Generated by Django 6.0.3 on 2026-08-01 15:15

import base.shared_enums.media_receiving_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_receiving', '0003_task_rewrite_alter_task_source_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(base.shared_enums.media_receiving_model.TaskStatusEnum['AWAITING'], 'Wait for processing…'), (base.shared_enums.media_receiving_model.TaskStatusEnum['DONE'], 'Done!'), (base.shared_enums.media_receiving_model.TaskStatusEnum['ERROR'], 'ERROR!!!'), (base.shared_enums.media_receiving_model.TaskStatusEnum['PROCESSING'], 'Processing…'), (base.shared_enums.media_receiving_model.TaskStatusEnum['DISCARDED'], 'Discarded')], default=base.shared_enums.media_receiving_model.TaskStatusEnum['AWAITING']),
        ),
    ]
